CREATE DATABASE chippy
CREATE TABLE orders(
id INT(11) U AUTO_INCREMENT PRIMARY KEY,
textBox VARCHAR(150) NOT NULL,
fullName VARCHAR(150) NOT NULL,
email VARCHAR(150) NOT NULL,
address VARCHAR(150) NOT NULL,
tele VARCHAR(17) NOT NULL,
plate int(50) NOT NULL,
status VARCHAR (20) NOT NULL,
created_date DATETIME NOT NULL,
);



CREATE TABLE contact (
id INT(11) AUTO_INCREMENT PRIMARY KEY,
fullname VARCHAR(150) NOT NULL,
email VARCHAR(150),
message VARCHAR(750),
created_date DATETIME NOT NULL,
);

CREATE TABLE signin (
id INT(11)  AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(150) NOT NULL,
password VARCHAR(50) NOT NULL,
);
INSERT INTO signin (username, password)
VALUES ('jumoke', md5('jummy123');